# Generated by Django 4.2.30 on 2026-06-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('hr', 'HR'), ('employee', '员工'), ('interviewer', '面试官')], default='employee', max_length=20, verbose_name='角色'),
        ),
    ]
