# Generated by Django 4.2.30 on 2026-06-12 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='职位名称')),
                ('department', models.CharField(max_length=100, verbose_name='所属部门')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='工作地点')),
                ('salary_range', models.CharField(blank=True, default='', max_length=100, verbose_name='薪资范围')),
                ('description', models.TextField(verbose_name='职位描述')),
                ('requirements', models.TextField(blank=True, default='', verbose_name='任职要求')),
                ('status', models.CharField(choices=[('open', '招聘中'), ('closed', '已关闭')], default='open', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_jobs', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100, verbose_name='候选人姓名')),
                ('candidate_email', models.EmailField(max_length=254, verbose_name='候选人邮箱')),
                ('candidate_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='候选人电话')),
                ('resume', models.FileField(upload_to='resumes/', verbose_name='简历')),
                ('cover_letter', models.TextField(blank=True, default='', verbose_name='推荐语')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('reviewing', '审核中'), ('accepted', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='jobs.job', verbose_name='职位')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='推荐人')),
            ],
            options={
                'verbose_name': '内推',
                'verbose_name_plural': '内推',
                'ordering': ['-created_at'],
            },
        ),
    ]
