# Generated by Django 4.2.30 on 2026-06-13 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('first_interview', '初试'), ('second_interview', '复试'), ('accepted', '已通过'), ('rejected', '已淘汰')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='jobs.referral', verbose_name='关联内推')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('first_interview', '初试'), ('second_interview', '复试'), ('accepted', '已通过'), ('rejected', '已淘汰')], max_length=20, verbose_name='阶段状态')),
                ('feedback', models.TextField(verbose_name='反馈简报')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 星'), (2, '2 星'), (3, '3 星'), (4, '4 星'), (5, '5 星')], verbose_name='评分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='jobs.referral', verbose_name='内推记录')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '候选人进度',
                'verbose_name_plural': '候选人进度',
                'ordering': ['created_at'],
            },
        ),
    ]
