# Generated by Django 4.2.30 on 2026-06-13 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_alter_referral_status_notification_candidateprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(choices=[('first', '初试'), ('second', '复试'), ('third', '终试')], default='first', max_length=20, verbose_name='面试轮次')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='面试时间')),
                ('status', models.CharField(choices=[('pending', '待面试'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL, verbose_name='面试官')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobs.referral', verbose_name='内推记录')),
            ],
            options={
                'verbose_name': '面试',
                'verbose_name_plural': '面试',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_score', models.PositiveSmallIntegerField(default=0, help_text='1-10分', verbose_name='技术能力')),
                ('communication_score', models.PositiveSmallIntegerField(default=0, help_text='1-10分', verbose_name='沟通能力')),
                ('teamwork_score', models.PositiveSmallIntegerField(default=0, help_text='1-10分', verbose_name='团队协作')),
                ('problem_solving_score', models.PositiveSmallIntegerField(default=0, help_text='1-10分', verbose_name='问题解决能力')),
                ('cultural_fit_score', models.PositiveSmallIntegerField(default=0, help_text='1-10分', verbose_name='文化适配')),
                ('learning_ability_score', models.PositiveSmallIntegerField(default=0, help_text='1-10分', verbose_name='学习能力')),
                ('overall_comment', models.TextField(blank=True, default='', verbose_name='综合评价')),
                ('strengths', models.TextField(blank=True, default='', verbose_name='优点')),
                ('weaknesses', models.TextField(blank=True, default='', verbose_name='待改进点')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='总分')),
                ('recommendation', models.CharField(blank=True, choices=[('pass', '推荐进入下一轮'), ('fail', '不推荐'), ('hold', '待定')], default='', max_length=20, verbose_name='建议')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('evaluated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL, verbose_name='评价人')),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='jobs.interview', verbose_name='面试')),
            ],
            options={
                'verbose_name': '面试评价',
                'verbose_name_plural': '面试评价',
                'ordering': ['-created_at'],
            },
        ),
    ]
